### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by sammdec** [ornicar/php-git-repo#10]
I have a small php script that I run but want to be able to issue git commands from the script. From the looks of things this will work. But how do i include the lib folder into my project.

**Comment by ornicar** [comment]
using `require_once`

**Comment by sammdec** [comment]
ah that I do know but what file do I require as there are 3 files?

**Comment by ornicar** [comment]
experiment and draw conclusions. that's how you'll learn.

**Comment by sammdec** [comment]
Ok thanks very much. I am more than happy to experiment I just dont want to find an old style of doing something when a new and better thing is out there as it forms bad habits.
