### ISSUE TITLE
Use git plumbing commands

### ISSUE THREAD

**Issue by dolmen** [ornicar/php-git-repo#11]
Git has [two kinds of commands](http://git-scm.com/book/en/Git-Internals-Plumbing-and-Porcelain):
- porcelain for humans
- plumbing for programs

PHPGitRepo should use the plumbing commands instead of the porcelain commands.

The `getBranches` method has this issue.

**Comment by ornicar** [comment]
You're right, but I don't maintain that project anymore. Feel free to fork and improve as needed.
