### ISSUE TITLE
Failed with code 1?

### ISSUE THREAD

**Issue by mykdavis** [ornicar/php-git-repo#14]
Just tried to set this up locally and got the following just doing a git status:

Fatal error: Uncaught exception 'GitRuntimeException' with message 'Command cd "C:\xampp\htdocs\vs-core-develop" && /usr/bin/git status failed with code 1: ' in C:\xampp\htdocs\vs-core-develop\gitphp\Command.php:59 Stack trace: #0 C:\xampp\htdocs\vs-core-develop\gitphp\Repository.php(241): PHPGit_Command->run() #1 C:\xampp\htdocs\vs-core-develop\includes\application_top.php(1832): PHPGit_Repository->git('status') #2 C:\xampp\htdocs\vs-core-develop\index.php(3): require('C:\xampp\htdocs...') #3 C:\xampp\htdocs\vs-templates-integration\controller.php(92): require('C:\xampp\htdocs...') #4 {main} thrown in C:\xampp\htdocs\vs-core-develop\gitphp\Command.php on line 59

Any ideas??

**Comment by edwines** [comment]
It seems you didn't have GIT installed... or maybe you have it but in a virtual environment like cygwin.
