### ISSUE TITLE
packagist 

### ISSUE THREAD

**Issue by bazo** [ornicar/php-git-repo#8]
hi,

could you add this library as a package to packagist as you have done with some of your other libraries?

**Comment by ornicar** [comment]
I have done nothing, people submitted pull requests. You are welcome to do so!

**Comment by umpirsky** [comment]
But since git repo is under ornicar namespace, it would be nice to be submitted by ornicar user to packagist. Right?

**Comment by edwines** [comment]
@ornicar can you add this repo in packagist?... we can't do it because no one of us have access to setup the auto-update hook.

Thanks!

**Comment by ornicar** [comment]
I'm not using nor maintaining this project since years. What about I give you credentials so you can do the packagist thing?

**Comment by edwines** [comment]
Ok, I can do it.

**Comment by ornicar** [comment]
Thank you. You are now a collaborator on this project. I hope it lets you configure the service hooks.

**Comment by edwines** [comment]
mmm, but still I have no access to the service hook. But this repository does not have many updates, so I think no matter leave it the auto-update.

**Comment by ornicar** [comment]
if you tell me what to paste in the fields `user`, `token` and `domain` then I can set it up

**Comment by edwines** [comment]
user `edwines_`
token `************`

The domain is not required, it will be work with the default value.

**Comment by ornicar** [comment]
done!
